apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-pixel-fastapi
  namespace: blue-green-pixels
  labels:
    app: green-pixel-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-pixel-fastapi
  template:
    metadata:
      labels:
        app: green-pixel-fastapi
    spec:
      containers:
        - name: green-pixel-fastapi
          image: ghcr.io/idan-fishman/blue-green-pixels-green-pixel-fastapi:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
