apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue-green-pixels
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blue-pixel-fastapi
                port:
                  number: 8000
