version: "3.9"

services:
  web:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword123
      POSTGRES_DATABASE: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
